name = "worker-new-girl"
main = "src/index.ts"
compatibility_date = "2023-04-20"

[env.dev.vars]
FAUNA_SECRET = "fnAFCCznjeAATXszZR6chXVs0v4-8o5c3yn8mKcb"
SHOW_INFO_ID = "365484020443643981"
ENVIRONMENT = "dev"

[env.dev]
name = "worker-new-girl-dev"