name = "worker-new-girl"
main = "src/index.ts"
compatibility_date = "2023-04-20"

[vars]
SHOW_INFO_ID = "365484020443643981"

[env.dev.vars]
# FAUNA_SECRET = 
SHOW_INFO_ID = "365484020443643981"
ENVIRONMENT = "dev"

[env.dev]
name = "worker-new-girl-dev"