name: Deploy to Cloudflare

on:
  push:
    branches: [master]
    paths-ignore: [README.md, .gitignore, .github/workflows/unit-test.yml]

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
