name: Deploy to Cloudflare

on:
  workflow_run:
    workflows: [Unit Test CI]
    types:
      - completed
    branches: [master, dev]

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # i think its losing the branch name from the previous workflow
    # // could i use the last branch name from the previous workflow or check what had the last push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Echo branch name
        run: echo ${{ github.ref }}

      - name: Deploy to environment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: ${{ github.ref == 'refs/heads/dev' && 'deploy --env dev' || 'publish'}}

      - name: Which environment deployed?
        run: echo ${{ github.ref == 'refs/heads/dev' && 'dev' || 'prod'}}
