name: Deploy to Cloudflare

on:
  # workflow_run:
  #   workflows: [Unit Test CI]
  #   types:
  #     - completed
  #   branches: [master, dev]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - dev

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Echo branch name
        run: echo ${{ github.ref }}

      - name: Deploy to environment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: ${{ github.ref == 'refs/heads/dev' && 'deploy --env dev' || 'publish'}}

      - name: Which environment deployed?
        run: echo ${{ github.ref == 'refs/heads/dev' && 'dev' || 'prod'}}
