name: Unit Test CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    name: Unit Test CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log vars
        run: |
          echo $FAUNA_SECRET
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
        env:
          FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}
          SHOW_INFO_ID: ${{ secrets.SHOW_INFO_ID }}
          V10_FAUNA_SECRET: ${{ secrets.V10_FAUNA_SECRET }}
