name: Unit Test CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

env:
  FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}

jobs:
  test:
    name: Unit Test CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log vars
        run: |
          echo $FAUNA_SECRET

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test
        env:
          FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}
